version: '2'

services:
  cassandra:
    container_name: cassandra
    image: bitnami/cassandra:latest
    ports:
      - 9042:9042
    volumes:
      - cassandra_data:/bitnami
  mqtt-connector:
    container_name: connector
    build: ./mqtt-connector

volumes:
  cassandra_data:
    driver: local