{
 "title": "Filter by Board",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "board_uuid",
    "label": "Board UUID",
    "query": "101A-4F4F-8F69-6B8F3C2E78ED, 102A-4F4F-8F69-6B8F3C2E78ED, 103A-4F4F-8F69-6B8F3C2E78ED, 033A-4F4F-8F69-6B8F3C2E78ED"
   }
  ]
 },
 "panels": [
  {
   "title": "Moisture 1 in Percent",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "keyspace": "myno",
     "target": "SELECT sensor_number, sensor_value, timestamp\nFROM sensor_moisture\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid'\nORDER BY timestamp DESC \nALLOW FILTERING;"
    }
   ]
  },
  {
   "title": "Moisture 2 in Percent",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "keyspace": "myno",
     "target": "SELECT sensor_number, sensor_value, timestamp\nFROM sensor_moisture\nWHERE sensor_number = 2 AND board_uuid = '$board_uuid'\nORDER BY timestamp DESC \nALLOW FILTERING;"
    }
   ]
  },
  {
   "title": "Moisture 3 in Percent",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "keyspace": "myno",
     "target": "SELECT sensor_number, sensor_value, timestamp\nFROM sensor_moisture\nWHERE sensor_number = 3 AND board_uuid = '$board_uuid'\nORDER BY timestamp DESC \nALLOW FILTERING;"
    }
   ]
  },
  {
   "title": "Humidity 1 in Percent",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "keyspace": "myno",
     "target": "SELECT sensor_number, sensor_value, timestamp\nFROM sensor_humidity\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid'\nORDER BY timestamp DESC \nALLOW FILTERING;"
    }
   ]
  },
  {
   "title": "Temperature 1 in Degree Celsius",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "keyspace": "myno",
     "target": "SELECT sensor_number, sensor_value, timestamp\nFROM sensor_temperature\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid'\nORDER BY timestamp DESC \nALLOW FILTERING;"
    }
   ]
  },
  {
   "title": "Pressure 1 in hPa",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "keyspace": "myno",
     "target": "SELECT sensor_number, sensor_value, timestamp\nFROM sensor_pressure\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid'\nORDER BY timestamp DESC \nALLOW FILTERING;"
    }
   ]
  },
  {
   "title": "Statistics Moisture 1 in Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Mean')), CAST(mean_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'moisture'\nALLOW FILTERING;\n"
    },
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Median')), CAST(median_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'moisture'\nALLOW FILTERING;\n"
    },
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Min')), CAST(min_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'moisture'\nALLOW FILTERING;\n"
    },
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Max')), CAST(max_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'moisture'\nALLOW FILTERING;\n"
    }
   ]
  },
  {
   "title": "Statistics Moisture 2 in Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 6 },
   "targets": [
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Mean')), CAST(mean_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 2 AND board_uuid = '$board_uuid' AND sensor_type = 'moisture'\nALLOW FILTERING;\n"
    },
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Median')), CAST(median_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 2 AND board_uuid = '$board_uuid' AND sensor_type = 'moisture'\nALLOW FILTERING;\n"
    },
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Min')), CAST(min_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 2 AND board_uuid = '$board_uuid' AND sensor_type = 'moisture'\nALLOW FILTERING;\n"
    },
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Max')), CAST(max_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 2 AND board_uuid = '$board_uuid' AND sensor_type = 'moisture'\nALLOW FILTERING;\n"
    }
   ]
  },
  {
   "title": "Statistics Moisture 3 in Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 6 },
   "targets": [
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Mean')), CAST(mean_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 3 AND board_uuid = '$board_uuid' AND sensor_type = 'moisture'\nALLOW FILTERING;\n"
    },
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Median')), CAST(median_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 3 AND board_uuid = '$board_uuid' AND sensor_type = 'moisture'\nALLOW FILTERING;\n"
    },
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Min')), CAST(min_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 3 AND board_uuid = '$board_uuid' AND sensor_type = 'moisture'\nALLOW FILTERING;\n"
    },
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Max')), CAST(max_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 3 AND board_uuid = '$board_uuid' AND sensor_type = 'moisture'\nALLOW FILTERING;\n"
    }
   ]
  },
  {
   "title": "Statistics Humidty 1 in Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 6 },
   "targets": [
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Mean')), CAST(mean_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'humidity'\nALLOW FILTERING;\n"
    },
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Median')), CAST(median_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'humidity'\nALLOW FILTERING;\n"
    },
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Min')), CAST(min_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'humidity'\nALLOW FILTERING;\n"
    },
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Max')), CAST(max_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'humidity'\nALLOW FILTERING;\n"
    }
   ]
  },
  {
   "title": "Statistics temperature 1 in Degree Celsius",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 6 },
   "targets": [
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Mean')), CAST(mean_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'temperature'\nALLOW FILTERING;\n"
    },
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Median')), CAST(median_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'temperature'\nALLOW FILTERING;\n"
    },
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Min')), CAST(min_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'temperature'\nALLOW FILTERING;\n"
    },
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Max')), CAST(max_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'temperature'\nALLOW FILTERING;\n"
    }
   ]
  },
  {
   "title": "Statistics Pressure 1 in hPa",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 6 },
   "targets": [
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Mean')), CAST(mean_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'pressure'\nALLOW FILTERING;\n"
    },
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Median')), CAST(median_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'pressure'\nALLOW FILTERING;\n"
    },
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Min')), CAST(min_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'pressure'\nALLOW FILTERING;\n"
    },
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Max')), CAST(max_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'pressure'\nALLOW FILTERING;\n"
    }
   ]
  },
  {
   "title": "Waterlevel 1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "keyspace": "myno",
     "target": "SELECT sensor_number, sensor_value, timestamp\nFROM sensor_waterlevel\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid'\nORDER BY timestamp DESC \nALLOW FILTERING;"
    }
   ]
  },
  {
   "title": "Brightness 1 in Lux",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "keyspace": "myno",
     "target": "SELECT sensor_number, sensor_value, timestamp\nFROM sensor_brightness\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid'\nORDER BY timestamp DESC \nALLOW FILTERING;"
    }
   ]
  },
  {
   "title": "Rain 1 in Percent",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "keyspace": "myno",
     "target": "SELECT sensor_number, sensor_value, timestamp\nFROM sensor_rain\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid'\nORDER BY timestamp DESC \nALLOW FILTERING;"
    }
   ]
  },
  {
   "title": "Statistics Waterlevel 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Mean')), CAST(mean_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'waterlevel'\nALLOW FILTERING;\n"
    },
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Median')), CAST(median_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'waterlevel'\nALLOW FILTERING;\n"
    },
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Min')), CAST(min_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'waterlevel'\nALLOW FILTERING;\n"
    },
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Max')), CAST(max_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'waterlevel'\nALLOW FILTERING;\n"
    }
   ]
  },
  {
   "title": "Statistics Birightness 1 in Lux",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Mean')), CAST(mean_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'brightness'\nALLOW FILTERING;\n"
    },
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Median')), CAST(median_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'brightness'\nALLOW FILTERING;\n"
    },
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Min')), CAST(min_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'brightness'\nALLOW FILTERING;\n"
    },
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Max')), CAST(max_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'brightness'\nALLOW FILTERING;\n"
    }
   ]
  },
  {
   "title": "Statistics Rain 1 in Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Mean')), CAST(mean_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'rain'\nALLOW FILTERING;\n"
    },
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Median')), CAST(median_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'rain'\nALLOW FILTERING;\n"
    },
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Min')), CAST(min_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'rain'\nALLOW FILTERING;\n"
    },
    {
     "keyspace": "myno",
     "target": "SELECT blobAsText(textAsBlob('Max')), CAST(max_value as double) as mean, toTimestamp(date) as time\nFROM sensor_statistics\nWHERE sensor_number = 1 AND board_uuid = '$board_uuid' AND sensor_type = 'rain'\nALLOW FILTERING;\n"
    }
   ]
  }
 ]
}